version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ssm,dynamodb
#  dynamo:
#    image: amazon/dynamodb-local:latest
#    ports:
#      - 8000:8000